### ISSUE TITLE
Default Projection

### ISSUE THREAD

**Issue by bradfox2** [nitxiodev/py-mongonnator#1]
Default projection ie. {}, does not return all fields.  It only returns the _id.

**Comment by nitxiodev** [comment]
You are completely right. `.find()` or `.find({})`, without any params, return every field from a given collection, but when you set specifically the `projection` parameter, mongo only returns the `_id`.

Thank you and I will update the readme to avoid misunderstanding.

**Comment by nitxiodev** [comment]
Done!
